server:
  port: 8081
spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    password: ${db_password}
    schema: classpath:/schema.sql
    url: jdbc:postgresql://localhost:5432/test_db
    username: ${db_user}
    validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
redis:
  database: 0
  hostname: localhost
  port: 6379
  password: ${redis_password}
  timeout: 30000
management:
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
  endpoints:
    web:
      exposure:
        include: health