server:
  port: 8081
spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    password: ${db_password}
    schema: classpath:/schema.sql
    url: jdbc:postgresql://localhost:5432/test_db
    username: ${db_user}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect